const enum ActionTypes {
    ADD_TO_HUNT = "ADD_TO_HUNT",
    REMOVE_FROM_HUNT = "REMOVE_FROM_HUNT",
    IMPORT = "IMPORT",
    SET_NAME = "SET_NAME",
    UPDATE_SURVIVOR = "UPDATE_SURVIVOR",
    UPDATE_SURVIVOR_STAT = "UPDATE_SURVIVOR_STAT",
    KILL_SURVIVOR = "KILL_SURVIVOR",
    REVIVE_SURVIVOR = "REVIVE_SURVIVOR",
    UPDATE_GEARGRID = "UPDATE_GEARGRID",
    UPDATE_GEARSLOT_AFFINITY = "UPDATE_GEARSLOT_AFFINITY",
    CREATE_SURVIVOR = "CREATE_SURVIVOR",
    RESET_HUNT = "RESET_HUNT",
}

export default ActionTypes;
