export const enum Innovations {
    advanced_combat_flanking,
    advanced_combat_shield_wall,
    albedo,
    altar,
    ammonia,
    arena,
    ars_moriendi,
    backpack,
    backpack_expanded,
    bandolier,
    bed,
    black_mask,
    bloodletting,
    bloodline,
    citrinitas,
    clan_of_death,
    cooking,
    crimson_candy,
    dark_water_research,
    drums,
    empire,
    face_painting,
    family,
    filleting_table,
    final_fighting_art,
    forbidden_dance,
    guidepost,
    hands_of_the_sun,
    heart_flute,
    hovel,
    inner_lantern,
    language,
    lantern_oven,
    legless_ball,
    momento_mori,
    nightmare_training,
    nigredo,
    paint,
    partnership,
    petal_spiral,
    pictograph,
    pottery,
    records,
    round_stone_training,
    rubedo,
    sacred_pool,
    sacrifice,
    saga,
    sauna_shrine,
    scarification,
    scrap_smelting,
    sculpture,
    settlement_watch,
    shadow_dancing,
    shrine,
    silk_refining,
    song_of_the_brave,
    stoic_statue,
    storytelling,
    subterranean_agriculture,
    symposium,
    ultimate_weapon,
    war_room,
    white_mask,
}

export interface IInnovation {
    id: Innovations;
    name: string;
    consequence_of?: Innovations;
    survival_limit?: number;
    survival_depart?: number;
    insanity_depart?: number;
    description: string;
}
